#!/bin/bash

OPTS=`getopt -o w:p: -l words:,passwords: -- "$@"`

if [ $? != 0 ] ; then
    echo "Failed parsing options." >&2
    exit 1
fi

eval set -- "$OPTS"

WORDS=6
PASSWORDS=1

while true
do
    case $1 in 
	-w|--words)
	    WORDS="$2"
	    shift 2
	    ;;
	-p|--passwords)
	    PASSWORDS="$2"
	    shift 2
	    ;;
	--)
	    shift
	    break
	    ;;
	*)
	    break
	    ;;
    esac
done

while [ $PASSWORDS -gt 0 ]
do
    shuf --random-source=/dev/urandom -n "$WORDS" /usr/share/dict/american-english | paste -s -d " "
    PASSWORDS=$(( $PASSWORDS - 1 ))
done
