#!/usr/bin/env bash

RPCPORT=9545
PASSWORD=$HOME/passwords/parity.pass
PID_FILE=$HOME/.parity/my_parity.pid
LOG="$HOME/.parity/my_parity:$(date +%F:%T).log"
ADDR=436e2e46aecd9e63a88ebdab05a7bf7841be4ed2

if [ -f $PID_FILE ]
then
    read PID < $PID_FILE
    if kill -0 $PID &>/dev/null
    then
	echo parity already running.
	exit 2
    fi
fi

echo Starting parity.
nohup parity --jsonrpc-port $RPCPORT --password $PASSWORD --unlock $ADDR </dev/null &>>$LOG &
echo $! > $PID_FILE
