#!/usr/bin/env bash

PID_FILE=$HOME/.ethereum/geth.pid

read PID < $PID_FILE
if kill -0 $PID &>/dev/null
then
    echo Shutting down geth.
    kill -s SIGINT $PID
    rm $PID_FILE
else
    echo geth not running.
fi
